account/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from account import AjaxView

app_name = "accounts"

urlpatterns = [
    # AJAX URLS
    path('update_cart', update_cart, name="update_cart_AJAX"),
    path('remove_basket_item', AjaxView.removeBasketItem, name="remove_basket_item"),
    path('remove_fav_items', AjaxView.removeFavItems, name="removeFavItems"),
    path('add_favorite_item', AjaxView.addFavoritesItem, name="addFavoritesItem"),
    path('apply_coupon/', AjaxView.apply_coupon, name="apply_coupon"),
    # END AJAX URLS
    path('sepetim', sepetim, name="myBasket"),
    path('favorilerim', favorilerim, name="myWishList"),
    path('odeme', checkout, name="checkout"),
    path('giris', loginView, name="login"),
    # iyzico and payment
    path('taksit_getir', taksit_getir, name="TaksitGetir"),
    path('checkout_done', csrf_exempt(checkout_done), name="checkout_done"),
    path('three-d-security', csrf_exempt(secure_view), name="secure_view"),
    path('cikis-yap', logout_view, name="logout"),

    path('password/', password, name='password'),  # <-- for social media auth
]

blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path('',blogList,name="blogListAll"),
    path('<slug:category>/',blogList,name="blogList"),
    path('<slug:category>/<slug:post>/',blogDetail,name="blogDetail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce import settings
from django.conf.urls.static import static
from home.views import homeView, searchView
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views as core_views

urlpatterns = [
    path('firsatlar/', include("campaings.urls")),  # < --- Campaign Urls
    path('blog/', include("blog.urls")),  # < --- Blog Urls
    path('hakkimizda', core_views.hakkimizda, name="hakkimizda"),  # < --- Hakkimizda Url
    path('sss', core_views.sss, name="sss"),  # < --- Hakkimizda Url

    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- for social media auth

    path('admin/', admin.site.urls),
    path('kullanici/', include('account.urls')),  # Account Urls
    path('ara/', searchView, name="searchView"),
    path('home/', include('home.urls')),

    path('', homeView, name="homeView"),
    path('', include('product.urls')),  # Product And Category urls
    path('chaining/', include('smart_selects.urls')),  # Django Smart Select
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    # AJAX REQUEST
    path('urun_fiyat_getir', urun_fiyat_getir, name="urun_fiyat_getir"),
    path('product_filter', product_filter, name="product_filter"),
    # END AJAX REQUEST
    path('<slug:slug>/', product_list, name="product_list"),  # Main Cat burada categoriler listelencek
    path('<slug:category>/<slug:product>/', product_detail, name="product_detail"),


]

templates/site/base/header/headerAll.html
{% load hometags %}
{% load static %}
{% load sorl_thumbnail %}
<header id="masthead" class="site-header header-v2">
    <div class="container">
        <div class="row">

            <!-- ============================================================= Header Logo ============================================================= -->
            <div class="header-logo">
                <a href="{% url 'homeView' %}" class="header-logo-link">
                    <img src="{{ site.logo.url }}" alt="{{ site.title }}" width="160" height="40" style="height: 50px;width: 160px">
                </a>
            </div>
            <!-- ============================================================= Header Logo : End============================================================= -->

            <div class="primary-nav animate-dropdown">
                <div class="clearfix">
                    <button class="navbar-toggler hidden-sm-up pull-right flip" type="button" data-toggle="collapse" data-target="#default-header">
                        ☰
                    </button>
                </div>

                <div class="collapse navbar-toggleable-xs" id="default-header">
                    <nav>
                        <ul id="menu-main-menu" class="nav nav-inline yamm">
                            <li class="menu-item"><a title="Home" href="{% url 'homeView' %}" aria-haspopup="true">Anasayfa</a></li>
                            <li class="menu-item animate-dropdown"><a title="Hakkımızda" href="{% url 'hakkimizda' %}">Hakkımızda</a></li>
                            <li class="menu-item animate-dropdown"><a title="Hakkımızda" href="{% url 'sss' %}">S.S.S</a></li>

                            <li class="menu-item"><a title="Blog" href="{% url 'blog:blogListAll' %}" aria-haspopup="true">Blog</a></li>
                            <li class="menu-item"><a title="Contact Us" href="#">İletişim</a></li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="header-support-info">
                <div class="media">
                    <span class="media-left support-icon media-middle"><i class="ec ec-support"></i></span>
                    <div class="media-body">
                        <span class="support-number"><strong>Destek</strong> {{ site.phone }}</span><br>
                        <span class="support-email">Email: {{ site.mail }}</span>
                    </div>
                </div>
            </div>

        </div><!-- /.row -->
    </div>
</header>
<nav class="navbar navbar-primary navbar-full">
    <div class="container">
        <ul class="nav navbar-nav departments-menu animate-dropdown">
            <li class="nav-item dropdown ">

                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="departments-menu-toggle">Kategoriler</a>
                <ul id="menu-vertical-menu" class="dropdown-menu yamm departments-menu-dropdown" style="">
                    {% for c in camps %}
                        <li class="highlight menu-item animate-dropdown active">
                            <a title="{{ c.title }}" href="{{ c.getUrl }}">{{ c.title }}</a>
                        </li>
                    {% endfor %}
                    {% for m in MainMenu %}
                        <li class="yamm-tfw menu-item menu-item-has-children animate-dropdown dropdown">
                            <a title="{{ m.title }}" data-hover="dropdown" href="{% url 'shop:product_list' m.slug %}"
                               data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">{{ m.title }}</a>
                            <ul role="menu" class=" dropdown-menu">
                                <li class="menu-item animate-dropdown menu-item-object-static_block">
                                    <div class="yamm-content">
                                        <div class="row bg-yamm-content bg-yamm-content-bottom bg-yamm-content-right">
                                            <div class="col-sm-12">
                                                <div class="vc_column-inner ">
                                                    <div class="wpb_wrapper">
                                                        <div class="wpb_single_image wpb_content_element vc_align_left">
                                                            <figure class="wpb_wrapper vc_figure">
                                                                <div class="vc_single_image-wrapper vc_box_border_grey">
                                                                    <img src="assets/images/megamenu-2.png"
                                                                         class="vc_single_image-img attachment-full"
                                                                         alt="">
                                                                </div>
                                                            </figure>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="vc_column-inner">
                                                    <div class="wpb_wrapper">
                                                        <div class="wpb_text_column wpb_content_element ">
                                                            <div class="wpb_wrapper">
                                                                <ul>
                                                                    {% for sub in SubMenu|filterSubAttr:m.id %}
                                                                        <li><a href="{% url 'shop:product_list' sub.slug %}">{{ sub.title }}</a>
                                                                        </li>
                                                                    {% endfor %}
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
        <form class="navbar-search" method="get" action="{% url 'searchView' %}">
            <label class="sr-only screen-reader-text" for="search">Search for:</label>
            <div class="input-group">
                <input type="text" id="search" class="form-control search-field" dir="ltr" value="" name="q"
                       placeholder="Search for products">
                <div class="input-group-addon search-categories">
                    <select name="product_cat" id="product_cat" class="postform resizeselect" style="width: 143px;">
                        <option value="0" selected="selected">Tüm Kategoriler</option>
                        {% for m in MainMenu %}
                            <option value="{{ m.slug }}">{{ m.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-group-btn">
                    <input type="hidden" id="search-param" name="post_type" value="product">
                    <button type="submit" class="btn btn-secondary"><i class="ec ec-search"></i></button>
                </div>
            </div>
        </form>
        <ul class="navbar-mini-cart navbar-nav animate-dropdown nav pull-right flip">
            <li class="nav-item dropdown">
                <a href="cart.html" class="nav-link" data-toggle="dropdown">
                    <i class="ec ec-shopping-bag"></i>
                    <span class="cart-items-count count">{{ basketItems.count }}</span>
                    <span class="cart-items-total-price total-price">&#8378; <span class="amount">{{ basketItems.0.parent_sepet.sepet_tutar }}</span></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-mini-cart">
                    <li>
                        <div class="widget_shopping_cart_content">
                            <ul class="cart_list product_list_widget ">
                                {% for i in basketItems %}
                                    <li class="mini_cart_item">
                                        <a title="Bu ürünü kaldır" class="remove" name="{{ i.id }}" href="javascript:void(0)">×</a>
                                        <a href="{{ i.parent_product.get_url }}">
                                            {% thumbnail i.parent_product.image '80x80' crop='center' as im %}
                                                <img class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image"
                                                     src="{{ im.url }}" alt="{{ i.parent_product.title }}">{{ i.parent_product.title }}
                                            {% endthumbnail %}
                                        </a>

                                        <span class="quantity"><span data-model-name="basketItemQty">{{ i.qty }}</span> ×  &#8378; <span data-model-name="basketItemPrice" class="amount">{{ i.price }}</span></span>
                                    </li>
                                {% endfor %}
                            </ul><!-- end product list -->
                            {% if basketItems.count > 0 %}
                                <p class="total1"><strong>Ara Toplam:</strong> &#8378;<span class="amount"> <span id="cartSubTotal">{{ basketItems.0.parent_sepet.sepet_tutar }}</span></span></p>
                                <p class="buttons">
                                    <a class="button wc-forward" href="{% url 'accounts:myBasket' %}">Sepetim</a>
                                    <a class="button checkout wc-forward" href="{% url 'accounts:checkout' %}">Ödeme</a>
                                </p>
                            {% else %}
                                <p class="total1"><span>Sepetinizde Henüz Ürün Yok</span></p>
                            {% endif %}


                        </div>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="navbar-wishlist nav navbar-nav pull-right flip">
            <li class="nav-item">
                <a href="{% url 'accounts:myWishList' %}" class="nav-link"><i class="ec ec-favorites"></i></a>
            </li>
        </ul>
        <ul class="navbar-compare nav navbar-nav pull-right flip">
            <li class="nav-item">
                <a href="compare.html" class="nav-link"><i class="ec ec-compare"></i></a>
            </li>
        </ul>
    </div>
</nav>

templates/site/base/header/headerIndex.html
{% load hometags %}
{% load thumbnail %}
<header id="masthead" class="site-header header-v1">
    <div class="container">
        <div class="row">

            <!-- ============================================================= Header Logo ============================================================= -->
            <div class="header-logo">
                <a href="{% url 'homeView' %}" class="header-logo-link">
                    <img src="{{ site.logo.url }}" alt="{{ site.title }}" width="160" height="40" style="height: 50px;width: 160px">
                </a>
            </div>
            <!-- ============================================================= Header Logo : End============================================================= -->

            <form class="navbar-search" method="get" action="{% url 'searchView' %}">
                <label class="sr-only screen-reader-text" for="search">Search for:</label>
                <div class="input-group">
                    <input type="text" id="search" class="form-control search-field" dir="ltr" value="" name="q"
                           placeholder="Ürünlerde Ara">
                    <div class="input-group-addon search-categories">
                        <select name="product_cat" id="product_cat" class="postform resizeselect" style="width: 143px;">
                            <option value="0" selected="selected">Tüm Kategoriler</option>
                            {% for m in MainMenu %}
                                <option value="{{ m.slug }}">{{ m.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-group-btn">
                        <input type="hidden" id="search-param" name="post_type" value="product">
                        <button type="submit" class="btn btn-secondary"><i class="ec ec-search"></i></button>
                    </div>
                </div>
            </form>
            <ul class="navbar-mini-cart navbar-nav animate-dropdown nav pull-right flip">
                <li class="nav-item dropdown">
                    <a href="{% url 'accounts:myBasket' %}" class="nav-link" data-toggle="dropdown">
                        <i class="ec ec-shopping-bag"></i>
                        <span class="cart-items-count count">{{ basketItems.count }}</span>
                        <span class="cart-items-total-price total-price">&#8378; <span class="amount">{{ basketItems.0.parent_sepet.sepet_tutar }}</span></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-mini-cart">
                        <li>
                            <div class="widget_shopping_cart_content">
                                <ul class="cart_list product_list_widget ">
                                    {% for i in basketItems %}
                                        <li class="mini_cart_item">
                                            <a title="Bu ürünü kaldır" class="remove" name="{{ i.id }}" href="javascript:void(0)">×</a>
                                            <a href="{{ i.parent_product.get_url }}">
                                                {% thumbnail i.parent_product.image '80x80' crop='center' as im %}
                                                    <img class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image"
                                                         src="{{ im.url }}" alt="{{ i.parent_product.title }}">{{ i.parent_product.title }}
                                                {% endthumbnail %}
                                            </a>

                                            <span class="quantity"><span data-model-name="basketItemQty">{{ i.qty }}</span> ×  &#8378; <span data-model-name="basketItemPrice" class="amount">{{ i.price }}</span></span>
                                        </li>
                                    {% endfor %}
                                </ul><!-- end product list -->
                                {% if basketItems.count > 0 %}
                                    <p class="total1"><strong>Ara Toplam:</strong> &#8378;<span class="amount"> <span id="cartSubTotal">{{ basketItems.0.parent_sepet.sepet_tutar }}</span></span></p>
                                    <p class="buttons">
                                        <a class="button wc-forward" href="{% url 'accounts:myBasket' %}">Sepetim</a>
                                        <a class="button checkout wc-forward" href="{% url 'accounts:checkout' %}">Ödeme</a>
                                    </p>
                                {% else %}
                                    <p class="total1"><span>Sepetinizde Henüz Ürün Yok</span></p>
                                {% endif %}


                            </div>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-wishlist nav navbar-nav pull-right flip">
                <li class="nav-item">
                    <a href="{% url 'accounts:myWishList' %}" class="nav-link"><i class="ec ec-favorites"></i></a>
                </li>
            </ul>
            <ul class="navbar-compare nav navbar-nav pull-right flip">
                <li class="nav-item">
                    <a href="compare.html" class="nav-link"><i class="ec ec-compare"></i></a>
                </li>
            </ul>
        </div><!-- /.row -->

        <div class="row">
            <div class="col-xs-12 col-lg-3">
                <nav>
                    <ul class="list-group vertical-menu yamm make-absolute">
                        <li class="list-group-item"><span><i class="fa fa-list-ul"></i> Kategoriler</span></li>
                        {% for m in MainMenu %}
                            <li class="yamm-tfw menu-item menu-item-has-children animate-dropdown dropdown">
                                <a title="{{ m.title }}" data-hover="dropdown" href="{% url 'shop:product_list' m.slug %}"
                                   data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">{{ m.title }}</a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li class="menu-item animate-dropdown menu-item-object-static_block">
                                        <div class="yamm-content">
                                            <div class="row bg-yamm-content bg-yamm-content-bottom bg-yamm-content-right">
                                                <div class="col-sm-12">
                                                    <div class="vc_column-inner ">
                                                        <div class="wpb_wrapper">
                                                            <div class="wpb_single_image wpb_content_element vc_align_left">
                                                                <figure class="wpb_wrapper vc_figure">
                                                                    <div class="vc_single_image-wrapper vc_box_border_grey">
                                                                        <img src="assets/images/megamenu-2.png"
                                                                             class="vc_single_image-img attachment-full"
                                                                             alt="">
                                                                    </div>
                                                                </figure>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <div class="vc_column-inner ">
                                                        <div class="wpb_wrapper">
                                                            <div class="wpb_text_column wpb_content_element ">
                                                                <div class="wpb_wrapper">
                                                                    <ul>
                                                                        {% for sub in SubMenu|filterSubAttr:m.id %}
                                                                            <li><a href="{% url 'shop:product_list' sub.slug %}">{{ sub.title }}</a>
                                                                            </li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        {% endfor %}


                    </ul>
                </nav>
            </div>

            <div class="col-xs-12 col-lg-9">
                <nav>
                    <ul id="menu-secondary-nav" class="secondary-nav">
                        {% for c in camps %}
                            <li class="highlight menu-item"><a href="{{ c.getUrl }}">{{ c.title }}</a></li>
                        {% endfor %}
                        <li class="menu-item animate-dropdown"><a title="Hakkımızda" href="{% url 'hakkimizda' %}">Hakkımızda</a></li>
                        <li class="menu-item animate-dropdown"><a title="SSS" href="{% url 'sss' %}">S.S.S</a></li>

                        <li class="menu-item"><a title="Blog" href="{% url 'blog:blogListAll' %}" aria-haspopup="true">Blog</a></li>
                        <li class="menu-item"><a title="Contact Us" href="#">İletişim</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header><!-- #masthead -->