blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path('',blogList,name="blogListAll"),
    path('<slug:category>/',blogList,name="blogList"),
    path('<slug:category>/<slug:post>/',blogDetail,name="blogDetail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce import settings
from django.conf.urls.static import static
from home.views import homeView, searchView
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views as core_views

urlpatterns = [
    path('firsatlar/', include("campaings.urls")),  # < --- Campaign Urls
    path('blog/', include("blog.urls")),  # < --- Blog Urls
    path('hakkimizda', core_views.hakkimizda, name="hakkimizda"),  # < --- Hakkimizda Url
    path('sss', core_views.sss, name="sss"),  # < --- Hakkimizda Url

    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- for social media auth

    path('admin/', admin.site.urls),
    path('kullanici/', include('account.urls')),  # Account Urls
    path('ara/', searchView, name="searchView"),
    path('home/', include('home.urls')),

    path('', homeView, name="homeView"),
    path('', include('product.urls')),  # Product And Category urls
    path('chaining/', include('smart_selects.urls')),  # Django Smart Select
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    # AJAX REQUEST
    path('urun_fiyat_getir', urun_fiyat_getir, name="urun_fiyat_getir"),
    path('product_filter', product_filter, name="product_filter"),
    # END AJAX REQUEST
    path('<slug:slug>/', product_list, name="product_list"),  # Main Cat burada categoriler listelencek
    path('<slug:category>/<slug:product>/', product_detail, name="product_detail"),


]

product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from home.models import AnaMenu, AltMenu
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Attribute, Sub_Attr, Detail, Brands, Files, Variant
from comment.models import ProductsComments
from django.contrib import messages
from django.core import serializers
import json, datetime, math
from decimal import Decimal
from django.http import HttpResponse
from django.db.models import Q
from account.models import Sepet, SepetUrunler
from account.templatetags.accoTags import get_client_ip
from campaings.models import Campaign
from home.views import filterByPrice, orderByProduct


# AJAX // JSON
def product_filter(request):
    price_min = request.GET.get("price_min")
    price_max = request.GET.get("price_max")
    slug = request.GET.get("slug")
    secimler = request.GET.getlist('secimler[]')
    page = int(request.GET.get("page"))
    perPageItem = int(request.GET.get("perPageItem"))
    brandss = request.GET.getlist("brandss[]")
    orderType = request.GET.get("orderBy")
    if AltMenu.objects.filter(slug=slug).exists():
        product = Product.objects.filter(sub_menu__slug=slug, active=True)
    else:
        return render(request, '404.html')
    product = filterByPrice(product, price_min, price_max, brandss)
    product = orderByProduct(orderType, product)
    for s in secimler:
        if s:
            filterList = []
            for sin in str(s).split(","):
                filterList.append(int(sin))
            product = product.filter(id__in=Detail.objects.filter(sub_attr__id__in=filterList).values("product__id")).distinct()
    gelen_sublar = Sub_Attr.objects.filter(id__in=Detail.objects.filter(product__in=product).values("sub_attr__id"),
                                           parent__in=Attribute.objects.filter(
                                               id__in=Detail.objects.filter(product__in=product).values("parent_attr__id"))).distinct()
    gelen_brands = Brands.objects.filter(id__in=product.values("brand__id"))
    filterSideBarAttr = Attribute.objects.filter(id__in=Detail.objects.filter(product__in=product).values("parent_attr__id").distinct())
    myp = sayfalama(request, product, perPageItem, page)
    myp = serializers.serialize("json", myp, fields=("title", "price", "slug", "info", "image", "voteAverage","code"))
    gelen_brands = serializers.serialize("json", gelen_brands, fields=('id', 'title'))
    gelen_sublar = serializers.serialize("json", gelen_sublar, fields=('id', 'title', 'parent'))
    filterSideBarAttr = serializers.serialize("json", filterSideBarAttr, fields=('id', 'name'))
    if math.ceil(product.count() / perPageItem) == 0:
        sayfa_sayim = 1
    else:
        sayfa_sayim = math.ceil(product.count() / perPageItem)
    data = json.dumps({
        'products': myp,
        'p_count': product.count(),
        'sayfa_sayisi': sayfa_sayim,
        'perPageItem': perPageItem,
        'gelen_sublar': gelen_sublar,
        'gelen_brands': gelen_brands,
        'filterSideBarAttr': filterSideBarAttr,
    })
    return HttpResponse(data)


# END AJAX / JSON


def product_list(request, slug):
    template = "site/product/ProductList.html"
    context = {}
    mainCat = AnaMenu.objects.filter(slug=slug, active=True)
    if mainCat:  # filter in main Category
        template = "site/product/category/allProductCategory.html"
        latestProduct = Product.latestProductsMainCat(Product, 5, slug)
        subMenus = AltMenu.objects.filter(active=True, parent__slug=slug)
        mostVoted = Product.mostVotedOnCategory(Product, slug, 15)
        context.update({'latestProduct': latestProduct, 'subMenus': subMenus, 'mostVoted': mostVoted})
        product_category(request, slug)
    else:
        content = Product.objects.filter(sub_menu__slug=slug, active=True).order_by(
            "-id")  # values("title", "slug", "image", "main_menu__title", "sub_menu__title", "price", "sub_menu__slug", "code", "main_menu__slug", "info", "stock")
        if not content:
            raise Http404("Herhangi bir Sayfa Bulunuamadı")
        attr = Attribute.getAttr(Attribute, content)
        subAttr = Sub_Attr.getSubAttr(Sub_Attr, content)
        brands = Brands.getBrandsInProducts(Brands, content.values("brand__id"))
        proCount = content.count()
        content = sayfalama(request, content, 3, 1)
        onerilenUrunler = Product.onerilenler(Product, slug)
        lastProduct = Product.latestProductsMainCat(Product, 3, content[0].main_menu.slug)
        context.update(
            {'products': content, 'oneriler': onerilenUrunler, 'attr': attr, 'subAttr': subAttr, 'brands': brands, 'proCount': proCount, 'lastProduct': lastProduct})
    return render(request, template, context=context)


def product_category(request, slug):
    template = "site/product/category/allProductCategory.html"
    content = AltMenu.objects.filter(active=True, parent__slug=slug)
    context = {
        'content': content
    }
    return render(request, template, context=context)


def product_detail(request, category, product):
    urun = get_object_or_404(Product, active=True, slug=product, main_menu__slug=category)
    discPrice = Decimal(urun.price) - Decimal(Campaign.calcDiscountPrice(Campaign, urun))
    urun_detaylar = Detail.objects.filter(product=urun)
    gallery = Files.getFilesProduct(Files, urun.id)
    relatedPro = Product.relatedProducts(Product, 8, urun.sub_menu.slug, urun.id)
    comments = ProductsComments.objects.filter(product__id=urun.id, active=True)
    camp = None
    if urun.disc_group:
        camp = Campaign.getCamp(Campaign, urun.disc_group.id)
    if request.method == "POST":
        if 'yorum_ekle' in request.POST:
            yorumEkle(request, urun)
        else:
            selected_details = []
            strVariantAttr = ""
            postQty = request.POST.get("qty", 1)
            for detay in urun_detaylar:
                if request.POST.get('selvaryant' + str(detay.id) + ''):
                    selected_details.append(int((request.POST.get('selvaryant' + str(detay.id) + ''))))
                    strVariantAttr += "%s : %s    " % (detay.parent_attr.name, Sub_Attr.objects.get(id=request.POST.get("selvaryant" + str(detay.id) + "")).title)
            if not SepetUrunler.has_product(SepetUrunler, Sepet.create_or_get_basket(Sepet, request.user, get_client_ip(request)), urun, selected_details, strVariantAttr):
                if Product.has_stock(Product, urun.id, postQty, selected_details):
                    basket_add_product(request, urun, postQty, strVariantAttr, selected_details)
                else:
                    messages.add_message(request, messages.INFO, "Stokta Yeterli Sayıda Ürün Yok")
            else:
                messages.add_message(request, messages.INFO, "Bu ürün daha önceden sepetinize eklenmiş. Sepetim Kısmından Adet Sayısını Güncelleyebilirsin")

    context = {
        'urun': urun,
        'attr': urun_detaylar,
        'gallery': gallery,
        'comments': comments,
        'discPrice': discPrice,
        'relatedPro': relatedPro,
        'camp': camp,
    }
    return render(request, "site/product/productDetail.html", context)


def sayfalama(request, content, perPageItem, page):
    paginator = Paginator(content, perPageItem)
    try:
        content = paginator.page(page)
    except PageNotAnInteger:
        content = paginator.page(1)
    except EmptyPage:
        content = paginator.page(paginator.num_pages)
    return content


def yorumEkle(request, urun):
    yorum = ProductsComments.addComment(ProductsComments, request.user, urun, request.POST.get("comment"), votes=request.POST.get("votes"))
    if yorum:
        messages.add_message(request, messages.SUCCESS, "Yorum eklendi yönetici onayından sonra burada görebilirsiniz")
    else:
        messages.add_message(request, messages.ERROR, "Yorum eklenirken hata oluştu")


def basket_add_product(request, urun, qty, attrText, selected_details):
    basket = Sepet.create_or_get_basket(Sepet, request.user, get_client_ip(request))
    # print(basket)
    basket_item = SepetUrunler.add_product(SepetUrunler, urun, qty, attrText, basket, selected_details)
    if basket_item:
        messages.add_message(request, messages.SUCCESS, "Ürün Sepetinize Eklendi")
    else:
        messages.add_message(request, messages.ERROR, "Ürün Sepete Eklenirken Hata Oluştu")


def urun_fiyat_getir(request):  # AJAX METHOD
    product_id = int(request.GET.get('product_id'))
    secimler = request.GET.getlist('secimler[]')
    post_product = Product.objects.get(pk=product_id)
    varyant = Variant.objects.filter(product__pk=product_id)
    indirimTutari = Campaign.calcDiscountPrice(Campaign, post_product)
    for item in range(len(secimler)):
        varyant = varyant.filter(sub_details__pk=secimler[item])
    try:
        vary_stok = varyant.get().qty
    except:
        vary_stok = post_product.stock
    try:
        var_price = Decimal(varyant.get().price + post_product.price) - indirimTutari
    except:
        var_price = Decimal(post_product.price) - indirimTutari
    # varyant = serializers.serialize("json", varyant,fields=('price',))
    data = json.dumps({
        'total': str(var_price),
        'normal_price': str(var_price + indirimTutari),
        'qty': vary_stok,
    })
    return HttpResponse(data)

templates/site/product/include/leftBrowseCatSideBar.html
{% load hometags %}
<aside class="widget woocommerce widget_product_categories electro_widget_product_categories">
    <ul class="product-categories ">
        <li class="product_cat"><span>Kategorileri Keşfet</span>
            <ul>
                {% for c in cats %}
                    <li class="cat-item cat-item-137"><a href="{% url 'shop:product_list' c.slug %}"><span class="child-indicator"></span>{{ c.title }}</a>
                        {% with subCats|filterSubAttr:c.id as subAt %}
                            <span class="count">({{ subAt.count }})</span>
                            <ul class="children" style="display: none;">
                                {% for sub in subAt %}
                                    <li class="cat-item cat-item-139">
                                        <a href="{% url 'shop:product_list' sub.slug %}"><span class="no-child"></span>{{ sub.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            </li>
                        {% endwith %}
                {% endfor %}
            </ul>
        </li>
    </ul>
</aside>

templates/site/product/include/leftLatestProduct.html
{% load thumbnail %}
{% load proTags %}
<aside class="widget widget_products">
    <h3 class="widget-title">Latest Products</h3>
    <ul class="product_list_widget">
        {% for p in lastProduct %}
            <li>
                {% thumbnail p.image '180x180' crop='center' as im %}
                    <a href="{% url 'shop:product_detail' p.main_menu__slug p.slug %}" title="{{ p.title }}">
                        <img width="180" height="180" src="{{ im.url }}"
                             class="wp-post-image" alt="{{ p.title }}"/><span class="product-title">{{ p.title }}</span>
                    </a>
                {% endthumbnail %}
                <span class="electro-price">
                {% with p.id|getProDiscedPricebyProID as discPrice %}
                    {% if discPrice != 0 %}
                        <ins><span class="amount">&#8378; {{ discPrice }}</span></ins>
                        <del><span class="amount">&#8378;{{ p.price }}</span></del>
                    {% else %}
                        <ins><span class="amount">&#8378; {{ p.price }}</span></ins>
                    {% endif %}

                {% endwith %}
                </span>
            </li>
        {% endfor %}
    </ul>
</aside>

templates/site/product/include/productFilter.html
{% load proTags %}
<aside class="widget widget_electro_products_filter" id="filter_by_attr">
    <h3 class="widget-title">Filters</h3>
    <aside class="widget woocommerce widget_layered_nav">
        <h3 class="widget-title">Markalar</h3>
        <ul>
            {% for b in brands %}
               <li class="checkbox"> <label><input type="checkbox" class="checkbox" id="brandF{{ b.id }}"  value="{{ b.id }}"> &nbsp;{{ b.title }} <span class="cr"><i class=""></i></span></label></li>
            {% endfor %}
        </ul>
    </aside>
    {% for a in attr %}
        <aside class="widget woocommerce widget_layered_nav">
            <h3 class="widget-title">{{ a.name }}</h3>
            <ul id="attrFilterByID{{ a.id }}" name="{{ a.id }}">
                {% for sub in subAttr|filterSubAttr:a.id %}
                    <li class="checkbox">
                        <label><input type="checkbox" class="checkbox" id="varyant{{ sub.id }}" name="{{ sub.id }}" value="{{ sub.id }}" data-model-name="{{ a.id }}"> &nbsp;{{ sub.title }}
                            <span class="cr"><i class=""></i></span>
                        </label>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endfor %}

    <aside class="widget woocommerce widget_price_filter">
        <h3 class="widget-title">Fiyat</h3>
        <form action="#">
            <div class="row">
                <div class="col">
                    <input type="text" name="minPrice" id="minPrice" class="form-control" placeholder="Min Price">
                </div>
                <div class="col">
                    <input type="text" id="maxPrice" name="maxPrice" class="form-control" placeholder="Max Price">
                </div>
                <div class="col">
                    <div class="price_slider_amount">
                    <a href="#" class="button">Filter</a>
                    <div class="clear"></div>
                </div>
                </div>
            </div>
        </form>
    </aside>
</aside>

templates/site/product/include/productTabPanel.html
{% load thumbnail %}
{% load proTags %}
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">
        <ul class="products columns-3">
            {% for p in products %}
                <li class="product">
                    <div class="product-outer">
                        <div class="product-inner">
                            <span class="loop-product-categories"><a href="{% url 'shop:product_list' p.sub_menu.slug %}" rel="tag">{{ p.sub_menu.title }}</a></span>
                            <a href="{{ p.get_url }}">
                                <h3>{{ p.title }}</h3>
                                <div class="product-thumbnail">
                                    {% thumbnail p.image '240x220' crop='center' as im %}
                                        <img data-echo="{{ im.url }}"
                                             src="{{ im.url }}" alt="{{ p.title }}">
                                    {% endthumbnail %}
                                </div>
                            </a>
                            <div class="price-add-to-cart">
                                <span class="price">
                                    <span class="electro-price">
                                        {% if p.disc_price %}
                                            <ins><span class="amount">&#8378; {{ p.disc_price }}</span></ins>
                                            <del><span class="amount">&#8378; {{ p.price }}</span></del>
                                        {% elif p.disc_group %}
                                            <ins><span class="amount">&#8378; {{ p.price|calcDiscountPrice:p.disc_group.discPercentage }}</span></ins>
                                            <del><span class="amount">&#8378; {{ p.price }}</span></del>
                                        {% else %}
                                            <span class="amount">&#8378; {{ p.price }}</span>
                                        {% endif %}
                                    </span>
                                </span>
                                <a rel="nofollow" href="{{ p.get_url }}" class="button add_to_cart_button">Add
                                    to cart</a>
                            </div><!-- /.price-add-to-cart -->

                            <div class="hover-area">
                                <div class="action-buttons">
                                    <a href="javascript:void(0);" rel="nofollow" class="add_to_wishlist" name="{{ p.id }},{{ request.user.id }}">Wishlist</a>
                                    <a href="#" class="add-to-compare-link">Compare</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.product-inner -->
                    </div><!-- /.product-outer -->
                </li>
            {% endfor %}


        </ul>
    </div>
    <div role="tabpanel" class="tab-pane" id="grid-extended" aria-expanded="true">
        <ul class="products columns-3">
            {% for p in products %}
                <li class="product">
                    <div class="product-outer">
                        <div class="product-inner">
                            <span class="loop-product-categories"><a href="{% url 'shop:product_list' p.sub_menu.slug %}" rel="tag">{{ p.sub_menu.title }}</a></span>
                            <a href="{{ p.get_url }}">
                                <h3>{{ p.title }}</h3>
                                <div class="product-thumbnail">
                                    {% thumbnail p.image '240x220' crop='center' as im %}
                                        <img class="wp-post-image" data-echo="{{ im.url }}"
                                             src="{{ im.url }}" alt="{{ p.title }}">
                                    {% endthumbnail %}
                                </div>

                                <div class="product-rating">
                                    <div title="Rated 4 out of 5" class="star-rating"><span
                                            style="width:80%"><strong class="rating">4</strong> out of 5</span>
                                    </div>
                                    (3)
                                </div>

                                <div class="product-short-description">
                                    {{ p.info|safe|slice:"150" }}..
                                </div>

                                <div class="product-sku">Ürün Kodu : {{ p.code }}</div>
                            </a>
                            <div class="price-add-to-cart">
                            <span class="price">
                                <span class="electro-price">
                                    <ins><span class="amount">&#8378; {{ p.price }}</span></ins>
                                </span>
                            </span>
                                <a rel="nofollow" href="{% url 'shop:product_detail' p.sub_menu.slug p.slug %}" class="button add_to_cart_button">
                                    Add to cart</a>
                            </div><!-- /.price-add-to-cart -->
                            <div class="hover-area">
                                <div class="action-buttons">
                                    <a href="#" rel="nofollow" class="add_to_wishlist" name="{{ p.id }},{{ request.user.id }}">Wishlist</a>
                                    <a href="#" class="add-to-compare-link">Compare</a>
                                </div>
                            </div>

                        </div><!-- /.product-inner -->
                    </div><!-- /.product-outer -->
                </li>
            {% endfor %}
        </ul>
    </div>
    <div role="tabpanel" class="tab-pane" id="list-view" aria-expanded="true">
        <ul class="products columns-3">
            {% for p in products %}
                <li class="product list-view">
                    <div class="media">
                        <div class="media-left">
                            <a href="{% url 'shop:product_detail' p.sub_menu.slug p.slug %}">
                                {% thumbnail p.image '300x210' crop='center' as im %}
                                    <img class="wp-post-image" data-echo="{{ im.url }}"
                                         src="{{ im.url }}" alt="{{ p.title }}">
                                {% endthumbnail %}
                            </a>
                        </div>
                        <div class="media-body media-middle">
                            <div class="row">
                                <div class="col-xs-12">
                                <span class="loop-product-categories">
                                    <a rel="tag" href="{% url 'shop:product_list' p.sub_menu.slug %}">{{ p.sub_menu__title }}</a></span><a
                                        href="{% url 'shop:product_detail' p.sub_menu.slug p.slug %}"><h3>{{ p.title }}</h3>
                                    <div class="product-rating">
                                        <div title="Rated 4 out of 5" class="star-rating"><span
                                                style="width:80%"><strong
                                                class="rating">4</strong> out of 5</span></div>
                                        (3)
                                    </div>
                                    <div class="product-short-description">
                                        {{ p.info|safe|slice:"150" }}..
                                    </div>
                                </a>
                                </div>
                                <div class="col-xs-12">

                                    <div class="availability in-stock">Stok : <span>{{ p.stock }}</span></div>
                                    <span class="price"><span class="electro-price"><span
                                            class="amount">&#8378; {{ p.price }}</span></span></span>
                                    <a class="button product_type_simple add_to_cart_button ajax_add_to_cart"
                                       data-product_sku="{{ p.code }}" data-product_id="{{ p.id }}" data-quantity="1"
                                       href="{% url 'shop:product_detail' p.sub_menu.slug p.slug %}" rel="nofollow">Add to cart</a>
                                    <div class="hover-area">
                                        <div class="action-buttons">
                                            <div class="yith-wcwl-add-to-wishlist add-to-wishlist-2706">
                                                <a class="add_to_wishlist" name="{{ p.id }},{{ request.user.id }}" data-product-type="simple"
                                                   data-product-id="{{ p.id }}" rel="nofollow" href="#">Wishlist</a>
                                                <div
                                                        class="yith-wcwl-wishlistaddedbrowse hide">
                                                    <span class="feedback">Product added!</span>
                                                    <a rel="nofollow" href="#">Wishlist</a>
                                                </div>
                                                <div
                                                        class="yith-wcwl-wishlistexistsbrowse hide">
                                                    <span class="feedback">The product is already in the wishlist!</span>
                                                    <a rel="nofollow" href="#" class="add_to_wishlist" name="{{ p.id }},{{ request.user.id }}">Wishlist</a>
                                                </div>
                                                <div style="clear:both"></div>
                                                <div class="yith-wcwl-wishlistaddresponse"></div>
                                            </div>
                                            <div class="clear"></div>
                                            <a data-product_id="{{ p.id }}" class="add-to-compare-link" href="#">Compare</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}


        </ul>
    </div>
    <div role="tabpanel" class="tab-pane" id="list-view-small" aria-expanded="true">

        <ul class="products columns-3">
            {% for p in products %}
                <li class="product list-view list-view-small">
                    <div class="media">
                        <div class="media-left">
                            <a href="{% url 'shop:product_detail' p.sub_menu.slug p.slug %}">
                                {% thumbnail p.image '145x90' crop='center' as im %}
                                    <img class="wp-post-image" data-echo="{{ im.url }}"
                                         src="{{ im.url }}" alt="{{ p.title }}">
                                {% endthumbnail %}
                            </a>
                        </div>
                        <div class="media-body media-middle">
                            <div class="row">
                                <div class="col-xs-12">
                                <span class="loop-product-categories">
                                <a rel="tag" href="{% url 'shop:product_list' p.sub_menu.slug %}">{{ p.sub_menu.title }}</a></span>
                                    <a href="{% url 'shop:product_list' p.sub_menu.slug %}"><h3>{{ p.title }}</h3>
                                        <div class="product-short-description">
                                            {{ p.info|safe|slice:"70" }}..
                                        </div>
                                        <div class="product-rating">
                                            <div title="Rated 4 out of 5" class="star-rating">
                                                <span style="width:80%"><strong class="rating">4</strong> out of 5</span></div>
                                            (3)
                                        </div>
                                    </a>
                                </div>
                                <div class="col-xs-12">
                                    <div class="price-add-to-cart">
                                        <span class="price"><span class="electro-price"><span class="amount">&#8378; {{ p.price }}</span></span></span>
                                        <a class="button add_to_cart_button" href="cart.html" rel="nofollow">Add
                                            to cart</a>
                                    </div><!-- /.price-add-to-cart -->

                                    <div class="hover-area">
                                        <div class="action-buttons">
                                            <a href="#" rel="nofollow" class="add_to_wishlist" name="{{ p.id }},{{ request.user.id }}">Wishlist</a>
                                            <a href="compare.html" class="add-to-compare-link">Compare</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>