account/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from account import AjaxView

app_name = "accounts"

urlpatterns = [
    # AJAX URLS
    path('update_cart', update_cart, name="update_cart_AJAX"),
    path('remove_basket_item', AjaxView.removeBasketItem, name="remove_basket_item"),
    path('remove_fav_items', AjaxView.removeFavItems, name="removeFavItems"),
    path('add_favorite_item', AjaxView.addFavoritesItem, name="addFavoritesItem"),
    path('apply_coupon/', AjaxView.apply_coupon, name="apply_coupon"),
    # END AJAX URLS
    path('sepetim', sepetim, name="myBasket"),
    path('favorilerim', favorilerim, name="myWishList"),
    path('odeme', checkout, name="checkout"),
    path('giris', loginView, name="login"),
    # iyzico and payment
    path('taksit_getir', taksit_getir, name="TaksitGetir"),
    path('checkout_done', csrf_exempt(checkout_done), name="checkout_done"),
    path('three-d-security', csrf_exempt(secure_view), name="secure_view"),
    path('cikis-yap', logout_view, name="logout"),

    path('password/', password, name='password'),  # <-- for social media auth
]

blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path('',blogList,name="blogListAll"),
    path('<slug:category>/',blogList,name="blogList"),
    path('<slug:category>/<slug:post>/',blogDetail,name="blogDetail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce import settings
from django.conf.urls.static import static
from home.views import homeView, searchView
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from home import views as core_views

urlpatterns = [
    path('firsatlar/', include("campaings.urls")),  # < --- Campaign Urls
    path('blog/', include("blog.urls")),  # < --- Blog Urls
    path('hakkimizda', core_views.hakkimizda, name="hakkimizda"),  # < --- Hakkimizda Url
    path('sss', core_views.sss, name="sss"),  # < --- Hakkimizda Url

    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- for social media auth

    path('admin/', admin.site.urls),
    path('kullanici/', include('account.urls')),  # Account Urls
    path('ara/', searchView, name="searchView"),
    path('home/', include('home.urls')),

    path('', homeView, name="homeView"),
    path('', include('product.urls')),  # Product And Category urls
    path('chaining/', include('smart_selects.urls')),  # Django Smart Select
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/site/base/base.html
{% load static %}
{% load hometags %}
<!DOCTYPE html>
<html lang="en-US" itemscope="itemscope" itemtype="http://schema.org/WebPage">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Electro &#8211; Electronics Ecommerce Theme</title>


    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.min.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-electro.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl-carousel.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/colors/yellow.css' %}" media="all"/>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,700italic,800,800italic,600italic,400italic,300italic' rel='stylesheet' type='text/css'>

    <link rel="shortcut icon" href="{% static 'assets/images/fav-icon.png ' %}">
    {% block meta %}

    {% endblock %}

</head>

<body class="single-product full-width">
<div id="page" class="hfeed site">
    <a class="skip-link screen-reader-text" href="#site-navigation">Skip to navigation</a>
    <a class="skip-link screen-reader-text" href="#content">Skip to content</a>

    <div class="top-bar">
        <div class="container">
            <nav>
                <ul id="menu-top-bar-left" class="nav nav-inline pull-left animate-dropdown flip">
                    <li class="menu-item animate-dropdown"><a title="Welcome to Worldwide Electronics Store" href="#">Türkiyenin Online Marketi</a></li>
                </ul>
            </nav>

            <nav>
                <ul id="menu-top-bar-right" class="nav nav-inline pull-right animate-dropdown flip">
                    <li class="menu-item animate-dropdown"><a title="Store Locator" href="#"><i class="ec ec-map-pointer"></i>Store Locator</a></li>
                    <li class="menu-item animate-dropdown"><a title="Track Your Order" href="track-your-order.html"><i class="ec ec-transport"></i>Track Your Order</a></li>
                    <li class="menu-item animate-dropdown"><a title="Shop" href="{% url 'homeView' %}"><i class="ec ec-shopping-bag"></i>Mağaza</a></li>
                    <li class="menu-item animate-dropdown"><a title="Blog" href="{% url 'blog:blogListAll' %}"><i class="fa fa-newspaper-o"></i>Blog</a></li>
                    <li class="menu-item animate-dropdown"><a title="Hesabım" href="{% url 'accounts:login' %}"><i class="ec ec-user"></i>Hesabım</a></li>
                </ul>
            </nav>
        </div>
    </div><!-- /.top-bar -->
    {% if request.get_full_path == "/" %}
        {% showHeaderIndex request %}
    {% else %}
        {% showHeaderForAll request %}
    {% endif %}




    <div id="content" class="site-content" tabindex="-1">
        {% block body %}

        {% endblock %}
    </div><!-- /.site-content -->


    {% showFooter %}

</div><!-- #page -->

<script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/tether.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/echo.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/electro.js' %}"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="{% static 'site/myCommerce.js' %}"></script>
{% block script %}

{% endblock %}

</body>
</html>

templates/site/base/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible" role="alert" id="message_box">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}